"use client";

import { ArtifactCard, Badge, Button, Command, CostMeter, Dialog, DiffView, Empty, Field, Input, Panel, PanelHeader, PhaseRail, Select, Sheet, Sparkline, StalenessBanner, Stat, StreamText, Table, Tabs, Textarea, Timeline, Toast, Tooltip } from "@kiln/ui";

const virtualRows = Array.from({ length: 140 }, (_, index) => [
  `Run ${String(index + 1).padStart(3, "0")}`,
  index % 11 === 0 ? "waiting" : index % 7 === 0 ? "running" : "succeeded",
  `£${(1.24 + index * 0.07).toFixed(2)}`,
]);

export function DesignGallery() {
  return (
    <div className="k-gallery">
      <Panel><PanelHeader title="Actions and states" meta="Every control uses the same 4px rhythm and 150ms state transition." /><div className="k-panel-body k-gallery-stack"><Button variant="primary">Primary</Button><Button>Secondary</Button><Button variant="ghost">Ghost</Button><Button variant="danger">Destructive</Button><Button size="sm">Compact</Button><Button disabled>Disabled</Button><Badge>neutral</Badge><Badge tone="accent">active</Badge><Badge tone="info">information</Badge><Badge tone="positive">healthy</Badge><Badge tone="warning">waiting</Badge><Badge tone="critical">failed</Badge><Tooltip label="A precise explanation, never a mystery icon."><Button size="sm">Hover for context</Button></Tooltip></div></Panel>
      <div className="k-gallery-grid">
        <Panel><PanelHeader title="Fields" /><div className="k-panel-body" style={{ display: "grid", gap: 16 }}><Field label="Venture name" htmlFor="gallery-name" hint="Shown to the customer."><Input id="gallery-name" defaultValue="Ember & Ash" /></Field><Field label="Playbook" htmlFor="gallery-playbook"><Select id="gallery-playbook" defaultValue="physical"><option value="physical">Physical commerce</option><option value="digital">Digital product</option><option value="service">Local service</option></Select></Field><Field label="Instruction" htmlFor="gallery-note" error="Say what must change."><Textarea id="gallery-note" rows={2} aria-invalid="true" /></Field></div></Panel>
        <Panel><PanelHeader title="Overlays" /><div className="k-panel-body k-gallery-stack"><Dialog trigger={<Button>Open dialog</Button>} title="Approve brand direction" description="The run remains paused until this is decided."><p>Dialog content is focused, labelled, and dismissible.</p></Dialog><Sheet trigger={<Button>Open sheet</Button>} title="Artifact details"><p>Sheets hold supporting detail without losing theatre context.</p></Sheet><Toast title="Neutral notice" body="The fixture replay is ready." /><Toast title="Connection restored" body="Shopify is current as of 09:42." tone="positive" /><Toast title="Approval expiring" body="Decision required in 2 hours." tone="warning" /><Toast title="Deploy failed" body="No live surface was changed." tone="critical" /></div></Panel>
        <Panel><PanelHeader title="Command" /><div className="k-panel-body"><Command items={[{ id: "run", label: "Open latest run", hint: "R" }, { id: "handover", label: "Start handover", hint: "H" }, { id: "export", label: "Export venture data", hint: "E" }]} /></div></Panel>
      </div>
      <Panel><PanelHeader title="Data" /><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(170px,1fr))" }}><Stat label="Revenue yesterday" value="£428" delta={{ value: 8.2, polarity: "up" }} asOf="12m ago" /><Stat label="Orders" value="17" delta={{ value: -2.4, polarity: "up" }} /><Stat label="Contribution margin" value="41.8%" /></div><div className="k-panel-body"><Sparkline label="Thirty-day revenue trend" values={[8, 12, 10, 17, 15, 24, 21, 29, 32, 30, 38]} /></div></Panel>
      <div className="k-gallery-grid">
        <Panel><PanelHeader title="Virtual table viewport" meta="140 rows; only the visible window is mounted." /><div className="k-panel-body"><Table caption="Run cost sample" columns={["Run", "Status", "Cost"]} rows={virtualRows} height={260} /></div></Panel>
        <Panel><PanelHeader title="Timeline" /><div className="k-panel-body"><Timeline items={[{ title: "Validation passed", meta: "09:14", tone: "positive" }, { title: "Critic rejected first draft", meta: "09:22", tone: "critical" }, { title: "Brand system accepted", meta: "09:31", tone: "positive" }]} /></div></Panel>
      </div>
      <Panel><PanelHeader title="Run primitives" /><div className="k-panel-body" style={{ display: "grid", gap: 18 }}><CostMeter spentMicros={3_420_000} budgetMicros={6_500_000} elapsed="47m elapsed" estimate="90m estimate" /><CostMeter spentMicros={5_480_000} budgetMicros={6_500_000} elapsed="78m elapsed" estimate="90m estimate" /><PhaseRail phases={[{ id: "1", title: "Succeeded", status: "succeeded" }, { id: "2", title: "Running", status: "running" }, { id: "3", title: "Blocked", status: "blocked" }, { id: "4", title: "Pending", status: "pending" }, { id: "5", title: "Failed", status: "failed" }, { id: "6", title: "Skipped", status: "skipped" }]} /><StreamText text="The complaint pattern is unusually specific: buyers do not object to the price; they object to not knowing whether the holder fits Japanese-core incense." /><StreamText complete text="The evidence set is complete and the recommendation has been written." /><ArtifactCard type="brand_system" version={2} status="accepted" selected quality={{ criticScore: 4.6 }} /><ArtifactCard type="content_set" version={1} status="review" quality={{ degraded: true, overridden: true, criticScore: 3.8 }} /></div></Panel>
      <Panel><PanelHeader title="Absence and staleness" meta="The two states that are easiest to leave unstyled and worst to meet unstyled." /><div className="k-panel-body" style={{ display: "grid", gap: 18 }}><Empty title="No ventures yet" body="The first one appears here as soon as intake completes." /><Empty title="Nothing to approve" body="Checkpoints arrive when a phase needs a decision." /><StalenessBanner provider="shopify" lastSyncedIso="2026-08-01T09:42:00.000Z" /><StalenessBanner provider="stripe" /></div></Panel>
      <div className="k-gallery-grid"><Panel><PanelHeader title="Diff view" /><div className="k-panel-body"><DiffView before="A beautifully crafted holder for every space." after="A 42mm stoneware rest sized for Japanese-core incense." /></div></Panel><Panel><PanelHeader title="Tabs and editorial type" /><div className="k-panel-body"><Tabs items={[{ id: "read", label: "Reading view", content: <p className="k-gallery-reading">Long-form artifacts use a real serif so strategy reads like an editorial document, not dashboard chrome.</p> }, { id: "raw", label: "Raw JSON", content: <pre>{`{ "criticScore": 4.6 }`}</pre> }]} /></div></Panel></div>
    </div>
  );
}
